/**
 * Created by chuck7 on 16/7/30.
 */
export const RECEIVE_ALL_POSTS = 'RECEIVE_ALL_POSTS'
export const POST_FOCUS = 'POST_FOCUS'
export const POST_EDIT = 'POST_EDIT'
export const POST_TITLE_EDIT = 'POST_TITLE_EDIT'
export const POST_SAVE = 'POST_SAVE'
export const POST_TITLE_SAVE = 'POST_TITLE_SAVE'
export const POST_DELETE = 'POST_DELETE'
export const POST_PUBLISH = 'POST_PUBLISH'
export const POST_CONTENT_UPDATE = 'POST_CONTENT_UPDATE'
export const POST_TITLE_UPDATE = 'POST_TITLE_UPDATE'
export const POST_EXCERPT_UPDATE = 'POST_EXCERPT_UPDATE'
export const POST_LAST_EDIT_TIME = 'POST_LAST_EDIT_TIME'
export const POST_TAG_UPDATE = 'POST_TAG_UPDATE'
export const POST_CREATE = 'POST_CREATE'

export const TOKEN_CREATE = 'TOKEN_CREATE'
export const TOKEN_DELETE = 'TOKEN_DELETE'
